development:
  adapter: postgresql
  database: berkeleygag_development
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: berkeleygag_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: berkeleygag_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test